name: Terraform Apply

on:
  push:
    branches:
      - production

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Terraform

    # Install Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_region: us-west-2
        run: echo "AWS credentials configured"

    # Configure Terraform
    - name: Configure Terraform
      run: |
        terraform init -input=false
        terraform workspace select production
        terraform providers lock -update

    # Apply Terraform
    #- name: Apply Terraform
    #  run: terraform apply -auto-approve
    #  env:
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_region: us-west-2
    